version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hackerone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h 0.0.0.0 -p 5432 -d hackerone -U postgres
      interval: 30s
      timeout: 30s
      retries: 500
      start_period: 3m
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py crontab add"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
